services:
  entry:
    image: traefik:v2.10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  next:
    image: awooooool/bego-table:latest
    build: .
    labels:
      - "traefik.enable=true"